name: GCC Toolchain Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install build-essential
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Populate toolchain
      run: make populate

    - name: Build RISC-V toolchain with -shared support
      run: make riscv64-unknown-elf-gcc

    - name: Build i686 toolchain
      run: make i686-unknown-elf-gcc

    - name: Build AMD64 toolchain
      run: make amd64-unknown-elf-gcc

    - name: Upload toolchains
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: cross-toolchains
        path: install/
